In [85]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [86]:
Data = pd.read_csv('D:\\New folder\\P1DATA.csv')
X = Data.iloc[:, 0:3].values
y = Data.iloc[:, 3:].values

In [87]:
print(X)

[['Milk' 200.0 24.0]
 ['Bread' 150.0 34.0]
 ['Choclate' 45.0 45.0]
 ['Cake' nan 18.0]
 ['Biscuite' 150.0 nan]
 ['Milk' 200.0 20.0]
 ['Choclate' 45.0 31.0]
 ['Biscuite' 150.0 nan]
 ['Bread' 150.0 19.0]]


In [88]:
print(y)

[['yes']
 ['yes']
 ['yes']
 ['yes']
 ['no']
 ['no']
 ['yes']
 ['yes']
 ['no']]


In [89]:
print(Data.isnull().sum())

Product name    0
Price           1
Age             2
Purchased       0
dtype: int64


In [90]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [91]:
print(X)

[['Milk' 200.0 24.0]
 ['Bread' 150.0 34.0]
 ['Choclate' 45.0 45.0]
 ['Cake' 136.25 18.0]
 ['Biscuite' 150.0 27.285714285714285]
 ['Milk' 200.0 20.0]
 ['Choclate' 45.0 31.0]
 ['Biscuite' 150.0 27.285714285714285]
 ['Bread' 150.0 19.0]]


In [92]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [93]:
print(X)

[[0.0 0.0 0.0 0.0 1.0 200.0 24.0]
 [0.0 1.0 0.0 0.0 0.0 150.0 34.0]
 [0.0 0.0 0.0 1.0 0.0 45.0 45.0]
 [0.0 0.0 1.0 0.0 0.0 136.25 18.0]
 [1.0 0.0 0.0 0.0 0.0 150.0 27.285714285714285]
 [0.0 0.0 0.0 0.0 1.0 200.0 20.0]
 [0.0 0.0 0.0 1.0 0.0 45.0 31.0]
 [1.0 0.0 0.0 0.0 0.0 150.0 27.285714285714285]
 [0.0 1.0 0.0 0.0 0.0 150.0 19.0]]


In [94]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

C:\Users\Raza Ali\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [95]:
print(y)

[1 1 1 1 0 0 1 1 0]


In [96]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X, y, test_size =0.2, random_state = 1)

In [97]:
print(X_train)

[[0.0 0.0 0.0 1.0 0.0 45.0 31.0]
 [1.0 0.0 0.0 0.0 0.0 150.0 27.285714285714285]
 [0.0 1.0 0.0 0.0 0.0 150.0 34.0]
 [0.0 0.0 0.0 0.0 1.0 200.0 24.0]
 [1.0 0.0 0.0 0.0 0.0 150.0 27.285714285714285]
 [0.0 0.0 1.0 0.0 0.0 136.25 18.0]
 [0.0 0.0 0.0 0.0 1.0 200.0 20.0]]


In [98]:
print(X_test)

[[0.0 1.0 0.0 0.0 0.0 150.0 19.0]
 [0.0 0.0 0.0 1.0 0.0 45.0 45.0]]


In [99]:
print(y_train)

[1 1 1 1 0 1 0]


In [100]:
print(y_test)

[0 1]


In [101]:
#using Standardization where 
# X - mean(x)/standard deviation(x)
# X subtract mean of (X) feature divide be standard deviation of feature (x)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 5:] = sc.fit_transform(X_train[:, 5:])
X_test[:, 5:] = sc.transform(X_test[:, 5:])

In [102]:
print(X_train)

[[0.0 0.0 0.0 1.0 0.0 -2.1293318643219066 0.9557993375161659]
 [1.0 0.0 0.0 0.0 0.0 0.055741671840887345 0.25436595272607676]
 [0.0 1.0 0.0 0.0 0.0 0.055741671840887345 1.5223416867696993]
 [0.0 0.0 0.0 0.0 1.0 1.096252879537456 -0.36613281074207865]
 [1.0 0.0 0.0 0.0 0.0 0.055741671840887345 0.25436595272607676]
 [0.0 0.0 1.0 0.0 0.0 -0.230398910275669 -1.4992175092491453]
 [0.0 0.0 0.0 0.0 1.0 1.096252879537456 -1.1215226097467899]]
